// Code generated by "stringer -type=Status"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NewlyInfected-1]
	_ = x[Susceptible-0]
	_ = x[Recovered - -1]
	_ = x[Vaccinated - -2]
	_ = x[Dead - -3]
}

const _Status_name = "DeadVaccinatedRecoveredSusceptibleNewlyInfected"

var _Status_index = [...]uint8{0, 4, 14, 23, 34, 47}

func (i Status) String() string {
	i -= -3
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+-3), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
