author: Asabs18 & davegi
year: 2022
useViper: true
license:
  header: This file is part of the `nantucket` project.
  text: |
    {{ .copyright }}

    Copying and distribution of this file, with or without modification,
    are permitted in any medium provided you do not contact the authors
    about the file or any problems you are having, or opinions you may have,
    with with the file.
